apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      namespace: development
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/pshenmic/ivend/frontend:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      imagePullSecrets:
      - name: gitlabregistrycred
