apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      namespace: development
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/pshenmic/ivend/frontend:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlabregistrycred
